### ISSUE TITLE
frame negativo en Animation

### ISSUE THREAD

**Issue by voices117** [fedemgp/Guerra-de-pijas#10]
al disparar en un angulo > 60 grados hay veces en las que el juego aborta por internar settearse un frame < 0 en animation:

    Thread 1 "client" received signal SIGABRT, Aborted.
    0x00007ffff65f3428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
    54	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
    (gdb) bt
    #0  0x00007ffff65f3428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
    #1  0x00007ffff65f502a in __GI_abort () at abort.c:89
    #2  0x00007ffff65ebbd7 in __assert_fail_base (fmt=<optimized out>, assertion=assertion@entry=0x46ac2f "frame >= 0", file=file@entry=0x46abc1 "libs/Animation.cpp", line=line@entry=102, 
    function=function@entry=0x46acc0 <GUI::Animation::setFrame(int)::__PRETTY_FUNCTION__> "void GUI::Animation::setFrame(int)") at assert.c:92
    #3  0x00007ffff65ebc82 in __GI___assert_fail (assertion=0x46ac2f "frame >= 0", file=0x46abc1 "libs/Animation.cpp", line=102, 
    function=0x46acc0 <GUI::Animation::setFrame(int)::__PRETTY_FUNCTION__> "void GUI::Animation::setFrame(int)") at assert.c:101
    #4  0x000000000045f98b in GUI::Animation::setFrame (this=0x6de6a8, frame=-8) at libs/Animation.cpp:102
    #5  0x000000000041824e in Ammo::Bullet::update (this=0x6de690, dt=0.0170000009) at src/client/Bullet.cpp:68
    #6  0x000000000040b287 in GUI::Game::update (this=0x7fffffffd1b0, dt=0.0170000009) at src/client/GUIGame.cpp:323
    #7  0x000000000040af7e in GUI::Game::start (this=0x7fffffffd1b0) at src/client/GUIGame.cpp:296
    #8  0x000000000042162f in main (argc=3, argv=0x7fffffffdb68) at src/client/main.cpp:27
    (gdb) 

Se observa que el valor del nuevo frame es "-8".

inspeccionando al llamador de la función se observa que "**angle**" es un valor negativo:

    #5  0x000000000041824e in Ammo::Bullet::update (this=0x6de690, dt=0.0170000009) at src/client/Bullet.cpp:68
    68	            this->animation.setFrame((int)std::floor(angle / angleStep));
    (gdb) p angle
    $3 = -90
    (gdb) p angleStep 
    $4 = 11.25
    (gdb)

**Comment by fedemgp** [comment]
Se arregló al corregir la forrma en que se serializaban las balas, conservando todas las balas hasta el final del turno.
