### ISSUE TITLE
Cargar desde yaml las armas

### ISSUE THREAD

**Issue by fedemgp** [fedemgp/Guerra-de-pijas#20]
El editor deberia devolver un archivo de configuración del mapa, en el que detalle la cantidad de municiones que tenga cada arma. Sería conveniente (por como se hizo del lado del servidor) que el archivo tenga un campo 'weapons', que sea una sequencia, y que cada nodo sea un mapa con 'name' y 'quantity' : <short number>  o 'infinity': <boolean> segun corresponda. Ejemplo:

weapons:
    - name: 'aerialAttack'
      quantity: 2
    - name: 'bazooka'
      infinity: true
    - name: 'grenade'
       quantity: 6

etcetera

**Comment by voices117** [comment]
se implementó como `weaponsAmmo` y se hizo un mapa donde la clave es el nombre del arma y el valor las municiones.

por el momento no se soporta "infinito".
